// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApk4QLRgu_BhnKqMczMJEmXMBb_DD7sdU',
    appId: '1:336013362570:web:494dc029f9fec6ea2ff473',
    messagingSenderId: '336013362570',
    projectId: 'pdpa-300',
    authDomain: 'pdpa-300.firebaseapp.com',
    storageBucket: 'pdpa-300.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoGbY7Zwl-z-wNxbYYbRvP-sCb2iLihRQ',
    appId: '1:336013362570:android:24f97568997e24352ff473',
    messagingSenderId: '336013362570',
    projectId: 'pdpa-300',
    storageBucket: 'pdpa-300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25P8p8nJ6DrEKJvxzii3IsT-_jLE7NEo',
    appId: '1:336013362570:ios:624079a4a9437dc52ff473',
    messagingSenderId: '336013362570',
    projectId: 'pdpa-300',
    storageBucket: 'pdpa-300.appspot.com',
    androidClientId: '336013362570-3kckn0n8n0fln2gtjpkh5bpog1qqi5qs.apps.googleusercontent.com',
    iosClientId: '336013362570-8gpsr2rgat43e3fbumgnn0t1n4a1lndt.apps.googleusercontent.com',
    iosBundleId: 'com.wisework.pdpa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD25P8p8nJ6DrEKJvxzii3IsT-_jLE7NEo',
    appId: '1:336013362570:ios:624079a4a9437dc52ff473',
    messagingSenderId: '336013362570',
    projectId: 'pdpa-300',
    storageBucket: 'pdpa-300.appspot.com',
    androidClientId: '336013362570-3kckn0n8n0fln2gtjpkh5bpog1qqi5qs.apps.googleusercontent.com',
    iosClientId: '336013362570-8gpsr2rgat43e3fbumgnn0t1n4a1lndt.apps.googleusercontent.com',
    iosBundleId: 'com.wisework.pdpa',
  );
}
